#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)
require 'gtd/read_review/cli'

begin
  exit_code = GTD::ReadReview::CLI.new(ARGV).run
  exit(exit_code || 0)
rescue GTD::ReadReview::MissingURL
  warn "Usage: gtd-read-review add URL"
  exit 1
rescue GTD::ReadReview::UnknownCommand => e
  warn "Unknown command: #{e.message}"
  warn "Run 'gtd-read-review help' for usage"
  exit 1
rescue GTD::ReadReview::Error => e
  warn "Error: #{e.message}"
  exit 1
end
