#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)
require 'gtd/email/cli'

begin
  exit_code = GTD::Email::CLI.new(ARGV).run
  exit(exit_code || 0)
rescue GTD::Email::MissingArgument => e
  warn "Error: #{e.message}"
  warn "Run 'gtd-email help' for usage"
  exit 1
rescue GTD::Email::UnknownCommand => e
  warn "Unknown command: #{e.message}"
  warn "Run 'gtd-email help' for usage"
  exit 1
rescue GTD::Email::Error => e
  warn "Error: #{e.message}"
  exit 1
end
