#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)
require 'gtd/calendar/cli'

begin
  exit_code = GTD::Calendar::CLI.new(ARGV).run
  exit(exit_code || 0)
rescue GTD::Calendar::UnknownCommand => e
  warn "Unknown command: #{e.message}"
  warn "Run 'gtd-calendar help' for usage"
  exit 1
rescue GTD::Calendar::Error => e
  warn "Error: #{e.message}"
  exit 1
end
